package com.ll.mango.admin.dao;

import com.ll.mango.admin.po.SysDept;
import org.springframework.stereotype.Repository;

@Repository
public interface SysDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Nov 28 09:56:44 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Nov 28 09:56:44 CST 2020
     */
    int insert(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Nov 28 09:56:44 CST 2020
     */
    int insertSelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Nov 28 09:56:44 CST 2020
     */
    SysDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Nov 28 09:56:44 CST 2020
     */
    int updateByPrimaryKeySelective(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Sat Nov 28 09:56:44 CST 2020
     */
    int updateByPrimaryKey(SysDept record);
}