package com.ll.mango.admin.dao;

import com.ll.mango.admin.po.SysUser;
import com.ll.mango.core.page.PageRequest;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.io.File;
import java.util.List;

@Repository
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 28 13:49:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 28 13:49:33 CST 2020
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 28 13:49:33 CST 2020
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 28 13:49:33 CST 2020
     */
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 28 13:49:33 CST 2020
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu May 28 13:49:33 CST 2020
     */
    int updateByPrimaryKey(SysUser record);

    /**
     * 查询全部
     *
     * @return
     */
    List<SysUser> findAll();

    /**
     * 分页查询
     *
     * @return
     */
    List<SysUser> findPage();

    List<SysUser> findByName(@Param(value = "name") String name);

    SysUser findByWholeName(String name);

    /**
     * 创建用户信息excel文件
     *
     * @param pageRequest
     * @return
     */
    File creatUserExcelFile(PageRequest pageRequest);


    List MtO();
}